name : "혼자서 runner 사용해보기"

on:
  push:
    branches: [ "master" ]

jobs:
  terraform_job:
    runs-on: self-hosted
    steps:
      - name: "Checkout code"  # 첫 번째 단계 (대시 '-' 필수)
        uses: actions/checkout@v4

      - name: "Terraform Apply"  # 두 번째 단계
        working-directory: ./
        run: terraform apply -auto-approve  # 대시 하나(-)가 표준입니다